; Normal / shared tier — więcej tenantów, mniejszy pool per proces
[www-shared]
user = container
group = container
listen = 9000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no

pm = dynamic
pm.max_children = 24
pm.start_servers = 6
pm.min_spare_servers = 4
pm.max_spare_servers = 12
pm.max_requests = 500
pm.status_path = /status-shared

request_terminate_timeout = 120
