[xdebug]
xdebug.mode=debug,profile
xdebug.start_with_request=trigger
xdebug.trigger_value=1
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.output_dir=/var/www/html/xdebug
xdebug.profiler_output_name=cachegrind.out.%p.%t
xdebug.trace_output_name=trace.%c.%p.%t

[PHP]
memory_limit = 1024M
post_max_size = 100M
upload_max_filesize = 100M
